config/routes.rb
Rails.application.routes.draw do
  # Public Routes
  root                      'main#index'
  get     'about'           => 'main#about'
  get     'portfolio'       => 'main#portfolio'
  get     'contact'         => 'main#contact'
  post    'contact'         => 'main#message'

  # Backend Routes
  get     'login'           => 'sessions#new'
  post    'login'           => 'sessions#create'
  delete  'logout'          => 'sessions#destroy'
  get     'admin'           => 'admin#index'
  get     'admin/messages', to: 'admin#messages', as: 'admin_messages'
end

app/models/message.rb
class Message < ActiveRecord::Base
  # Callbacks
  before_save {self.email.downcase!}

  # Validations

  # Name Regex source: http://stackoverflow.com/questions/2629422/rails-validating-full-name
  validates :first_name, :last_name, length: { maximum: 30 }, presence: true, format: { with: /\A[^0-9`!@#\$%\^&*+_=]+\z/ }

  # Email Regex source: https://www.railstutorial.org/book/modeling_users
  validates :email, length: { maximum: 255 }, presence: true, format: { with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i }

  validates :subject, length: { maximum: 30 }, presence: true

  validates :content, length: {maximum: 255},  presence: true

end

app/models/user.rb
class User < ActiveRecord::Base

  # Validations
  # Same as that of in message model
  validates :name, length: { maximum: 30 }, presence: true, format: { with: /\A[^0-9`!@#\$%\^&*+_=]+\z/ }

  # http://stackoverflow.com/a/336220 but ^ -> \A and $ -> \z, allows alphanumeric + underscores
  # I'll probably allow case sensitive usernames just to add entropy to whatever
  validates :username, length: { maximum: 30 }, presence: true, uniqueness: true, format: { with: /\A[a-zA-Z0-9_]*\z/ }

  validates :password, presence: true, length: { minimum: 10 }

  # make model use passwords
  has_secure_password

  # Creates a bcrypt hash of whatever
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  # Filter those who can access these parts
  before_action :logged_in_user

  # Use kickass admin layout
  layout "admin"

  def index
  end

  def messages
    # retrieve all message here
    @messages = Message.all.order(id: :desc)
  end

  private

  def logged_in_user
    unless logged_in?
      redirect_to root_url
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end

  def about
  end

  def portfolio
  end

  def contact
    @message = Message.new
  end

  def message
    @is_legit_user = verify_recaptcha
    @message = Message.new(get_message_params)
    if @message.save && @is_legit_user
      flash[:success] = "Thanks! I'll get back right at you at the speed of light!"
      redirect_to action: 'contact'
    else
      flash.now[:danger] = "Please click the little box down there. I have trust issues with bots :(" if !@is_legit_user
      flash.delete("recaptcha_error")
      render 'contact'
    end
  end

  private
    def get_message_params
      params.require(:message).permit(:first_name, :last_name, :email, :subject, :content)
    end
end

app/controllers/main_controller_controller.rb
class MainControllerController < ApplicationController
  def index
  end

  def about
  end

  def portfolio
  end

  def contact
    @message = Message.new
  end

  def message
    @is_legit_user = verify_recaptcha
    @message = Message.new(get_message_params)
    if @message.save && @is_legit_user
      flash[:success] = "Thanks! I'll get back right at you at the speed of light!"
      redirect_to action: 'contact'
    else
      flash.now[:danger] = "Please click the little box down there. I have trust issues with bots :(" if !@is_legit_user
      flash.delete("recaptcha_error")
      render 'contact'
    end
  end

  private
    def get_message_params
      params.require(:message).permit(:first_name, :last_name, :email, :subject, :content)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(username: params[:session][:username])
    legit_user = verify_recaptcha
    if legit_user && user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to admin_path
    else
      flash.now[:danger] = 'Invalid credentials'
      flash.delete("recaptcha_error")
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    session.key?(:user_id)
  end
end

app/views/admin/index.html.erb
<% provide(:title, 'Admin') %>

app/views/admin/messages.html.erb
<% provide(:title, 'Messages') %>
<div id="page-wrapper">
  <div class="container-admin">
    <% @messages.each do |message| %>
      <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
          <div class="panel panel-primary">
            <% title = "#{message[:subject]} || #{message[:first_name]} #{message[:last_name]} <#{message[:email]}> - #{message[:created_at]}" %>
            <div class="panel-heading">
              <%= content_tag(:h3, title, class: "panel-title") %>
            </div>
            <div class="panel-body">
              <%= message[:content] %>
            </div>
          </div>
        </div>
        <div class="col-md-2"></div>
      </div>
      <hr class="dashed"><br/>
    <% end %>
  </div>
</div>

app/views/layouts/_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-70432331-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <p class="text-muted text-center">Site Content &copy; <%=Time.now.year%> LA Roberto 
        <strong>·</strong> 
        <a href="https://github.com/teh-username/ninja-corgi">Source Code</a> licensed under <a href="https://github.com/teh-username/ninja-corgi/blob/master/LICENSE">MIT</a>.
    </p>

    <ul class="list-inline text-center">
        <li><a href="https://github.com/teh-username"><i class="fa fa-github fa-2x"></i></a></li>
        <li><a href="https://bitbucket.org/tehusername/"><i class="fa fa-bitbucket fa-2x"></i></a></li>
        <li><a href="https://ph.linkedin.com/in/laroberto"><i class="fa fa-linkedin-square fa-2x"></i></a></li>
    </ul>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="/">
        <span><%= image_tag('script_alt.svg', width: '36', height: '36', alt: "logo") %></span> LA Roberto
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'About Me', about_path %></li>
        <li><%= link_to 'Portfolio', portfolio_path %></li>
        <li><%= link_to 'Contact Me', contact_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_recaptcha.html.erb
<script src='https://www.google.com/recaptcha/api.js'></script>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js"></script>
<![endif]-->

app/views/layouts/_sidebar.html.erb
<!-- Most of the stuff here were ninja'd from https://github.com/IronSummitMedia/startbootstrap-sb-admin -->
<div class="container">
  <div id="wrapper">
    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">

      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <%= link_to(admin_path, class: "navbar-brand") do %>
            <span><i class="fa fa-fw fa-crosshairs fa-2x"></i></span> <%= current_user[:name] %>
          <% end %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to 'Home', root_path %></li>
            <li><%= link_to 'Log Out', logout_path, method: :delete %></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->

      <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
      <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav side-nav">
          <li>
            <%= link_to admin_path do %>
              <i class="fa fa-fw fa-dashboard"></i> Dashboard
            <% end %>
          </li>
          <li>
            <%= link_to admin_messages_path do %>
              <i class="fa fa-fw fa-envelope"></i> Messages
            <% end %>
          </li>
          <li>
            <a href="javascript:;" data-toggle="collapse" data-target="#configs"><i class="fa fa-fw fa-file-text-o"></i> Ara Configs<i class="fa fa-fw fa-caret-down"></i></a>
            <ul id="configs" class="collapse">
              <li>
                <a href="#">Stuffs 1</a>
              </li>
              <li>
                <a href="#">Stuffs 2</a>
              </li>
            </ul>
          </li>
        </ul>
      </div>
    </nav>
  </div>
</div>

app/views/layouts/admin.html.erb
<!-- Render Head -->
<% content_for :head do %>
  <!-- Other things to be rendered -->
  <% if content_for? :addtl_head %>
    <%= yield :addtl_head %>
  <% end %>

<% end %>

<!-- Render Body -->
<% content_for :body do %>
  <%= render 'layouts/sidebar' %>

  <% flash.each do |message_type, message| %>
    <%= content_tag(:div, message, class: "alert alert-#{message_type} text-center") %>
  <% end %>

  <%= yield %>
<% end %>

<!-- Render Base Template -->
<%= render template: "layouts/base" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link href='https://fonts.googleapis.com/css?family=Vollkorn' rel='stylesheet' type='text/css'>
    <title><%="#{yield(:title)} | LA Roberto"%></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
    <%= render 'layouts/analytics' %>
    <%= render 'layouts/recaptcha' if params['action'] == contact_path[1..-1] %>
    <%= favicon_link_tag 'favicon.ico' %>
  </head>
  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/layouts/base.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link href='https://fonts.googleapis.com/css?family=Vollkorn' rel='stylesheet' type='text/css'>
    <title><%="#{yield(:title)} | LA Roberto"%></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
    <%= content_for?(:head) ? yield(:head) : yield %>
    <%= favicon_link_tag 'favicon.ico' %>
  </head>
  <body>
    <%= content_for?(:body) ? yield(:body) : yield %>
  </body>
</html>

app/views/main/about.html.erb
<% provide(:title, 'About') %>
<div class="container">
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
      <h1><strong>More About Me</strong><small> (Yes, more) </small></h1>
      <p>I enjoy taking things apart and discovering how they work or taking a peek inside the hood of a framework to demystify the seemingly arcane arts that power it. On my spare time, I like to lurk on Reddit and post dank memes, play DnD 5e with a poorly role-played Wood-Elf Ranger, bunny hop (and fail miserably) my way around Dust_2 in CS:GO and discover something new everyday whether it be a TIL type of trivia or a new programming language. I'm a sucker for anything Star Wars and have been an avid follower of the series from the movies, print, games and the occasional TV Series. I am eternally curious about the masterful art of programming which brings me to work on little pet projects which (I hope) improves my skills further.</p>
    </div>
    <div class="col-md-2"></div>
  </div>
  <hr class="dashed">
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
      <h1><strong>Education</strong><small> (Street Creds) </small></h1>
      <p>I went to <abbr title="De La Salle University" class="initialism">DLSU</abbr> for my Bachelor's Degree in Computer Engineering which was made possible through a generous 100% tuition coverage scholarship provided by the University (for which I'm deeply grateful). Had not the scholarship been granted, plan B was to go to <abbr title="University of the Philippines" class="initialism">UP</abbr> instead. I was able to graduate with distinction (<a href="https://en.wikipedia.org/wiki/Latin_honors">cum laude</a>) and an <em>Outstanding Undergraduate Thesis Award</em> to boot. Our paper was entitled <em>Implementation of Speed and Torque Control on Quadrotor Altitude and Attitude Stability</em> which was published on <a href="http://www.ejournals.ph/index.php?journal=MJS&page=article&op=view&path%5B%5D=8069">The Manila Journal of Science</a> and the <a href="http://ieeexplore.ieee.org/xpl/articleDetails.jsp?tp&arnumber=7064345&queryText%3Dmagsino">13<sup>th</sup> International Conference on Control Automation Robotics and Vision (ICARCV)</a>. I was sort of active with regards to organizations within the University from which I once held the position <abbr title="Assistant Vice President" class="initialism">AVP</abbr> for Academics under the <abbr title="Association of Computer Engineering Students" class="initialism">ACCESS</abbr> organization. We were in-charge of providing academic support for my fellow Computer Engineering peers which includes me being a speaker/instructor on seminars planned by our committee such as beginner and advanced programming, embedded systems tutorials (prototyping and coding) and many more.</p> 
    </div>
    <div class="col-md-2"></div>
  </div>
  <hr class="dashed">
  <!-- I'm not particularly skilled at HTML as you can see below -->
  <div class="row skills-list">
    <div class="col-md-2"></div>
    <div class="col-md-8">
      <h1><strong>Skills</strong><small> (Utility Belt) </small></h1>
      <ul class="list-unstyled">
        <li>
          <h2>Hardware</h2>
          <ul>
            <li class="list-unstyled">
              <h3>Digital Circuits Design</h3>
              <ul>
                <li>Prototyping, PCB Implementation</li>
              </ul>
            </li>
            <li class="list-unstyled">
              <h3>Embedded Systems Development</h3>
              <ul>
                <li>Platform-specific (Arduino, RaspberryPI, Cubieboard),<br/>Microcontrollers (Atmel, Microchip)</li>
              </ul>
            </li>
          </ul>
        </li>
        <li>
          <h2>Software</h2>
          <ul>
            <li class="list-unstyled">
              <h3>Languages / Frameworks: </h3>
              <ul>
                <li>C / C++, C#, Java, Javascript (jQuery, NodeJS, ReactJS), <br/>PHP (Symfony2, Laravel, Kohana), Python, Ruby (Rails)</li>
              </ul>
            </li>
            <li class="list-unstyled">
              <h3>Version Control: </h3>
              <ul>
                <li>Git, SVN</li>
              </ul>
            </li>
            <li class="list-unstyled">
              <h3>Tools: </h3>
              <ul>
                <li>Apache Maven, Bower, Bundler, Browserify, Composer, Grunt, Jenkins, NPM, Rake, TravisCI, webpack</li>
              </ul>
            </li>
            <li class="list-unstyled">
              <h3>Database: </h3>
              <ul>
                <li>MySQL, SQLite</li>
              </ul>
            </li>
          </ul>
        </li>
      </ul>
    </div>
    <div class="col-md-2"></div>
  </div>
</div>

app/views/main/contact.html.erb
<% provide(:title, 'Contact Me') %>

<% content_for :addtl_head do %>
  <%= render 'layouts/recaptcha' %>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
      <h3 class="text-center">Have a quick message for me?</h3>
      <%= form_for(@message, url: contact_path, method: :post) do |f| %>
        <div class="form-group">
          <div class="row">
            <% msg = @message.errors.full_messages_for(:first_name) %>
            <div class="form-group <%= 'has-error' if msg.count > 0 %>">
              <div class="col-md-12">
                <%= f.label :name, 'Name*' %>
              </div>
              <div class="col-md-6">
                <%= f.text_field :first_name, class: "form-control", placeholder: "First Name please!", required: true %>
                <% if msg.count > 0 %>
                  <span class="help-block"><%= msg.first %></span>
                <% end %>
              </div>
            </div>
            <% msg = @message.errors.full_messages_for(:last_name) %>
            <div class="form-group <%= 'has-error' if msg.count > 0 %>">
              <div class="col-md-6">
                <%= f.text_field :last_name, class: "form-control", placeholder: "Last Name please!", required: true %>
                <% if msg.count > 0 %>
                  <span class="help-block"><%= msg.first %></span>
                <% end %>
              </div>
            </div>
          </div>
        </div>
        <% msg = @message.errors.full_messages_for(:email) %>
        <div class="form-group <%= 'has-error' if msg.count > 0 %>">
          <div class="row">
            <div class="col-md-12">
              <%= f.label :email, 'Contact Email*' %>
              <%= f.email_field :email, class: "form-control", placeholder: "I'll reply to this email", required: true %>
              <% if msg.count > 0 %>
              <span class="help-block"><%= msg.first %></span>
            <% end %>
            </div>
          </div>
        </div>
        <% msg = @message.errors.full_messages_for(:subject) %>
        <div class="form-group <%= 'has-error' if msg.count > 0 %>">
          <div class="row">
            <div class="col-md-12">
              <%= f.label :subject, 'Subject*' %>
              <%= f.text_field :subject, class: "form-control", placeholder: "Your message in a nutshell", required: true %>
              <% if msg.count > 0 %>
              <span class="help-block"><%= msg.first %></span>
            <% end %>
            </div>
          </div>
        </div>
        <% msg = @message.errors.full_messages_for(:content) %>
        <div class="form-group <%= 'has-error' if msg.count > 0 %>">
          <div class="row">
            <div class="col-md-12">
              <%= f.label :content, 'Message*' %>
              <%= f.text_area :content, class: "form-control", placeholder: "What do you want to say?", rows: 5, required: true %>
              <% if msg.count > 0 %>
              <span class="help-block"><%= msg.first %></span>
            <% end %>
            </div>
          </div>
        </div>
        <div class="form-group">
          <div class="row">
            <div class="col-md-12">
              <label for="message">Anti Bot Thingy*</label>
              <%= recaptcha_tags %>
            </div>
          </div>
        </div>
        <%= f.submit "Send!", class: "btn btn-default" %>
      <% end %>
    </div>
  </div>
  <div class="col-md-3"></div>
  <br/>
  <hr class="solid">
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
      <h3 class="text-center">Additional Details</h3><br/>
      <p>Need to talk to me about your take-over-the-world scheme? You can download my PGP Key <a href="https://drive.google.com/open?id=0B3U-QtOXlE9WaWlTcU1PNWFnMEk">here</a>.</p> <br/>
      <p>Found a bug/exploit on my site? I'd really appreciate it if you'd disclose it to me first before publishing it as an accomplishment. Just fill up the form above or submit a pull request <a href="https://github.com/teh-username/ninja-corgi">here</a>. As a sign that I'm eternally grateful, I'll be putting your name below this paragraph as proof you are a cool person! Thanks a lot!</p>
      <p>Cool Persons List: </p>
      <p>*tumbleweed*</p>
    </div>
    <div class="col-md-2"></div>
  </div>
</div>

app/views/main/index.html.erb
<% provide(:title, 'Home') %>
<div class="jumbotron">
  <div class="container">
    <h1 class="text-center">Developer</h1>
    <ul class="list-inline text-center">
      <li>Computer Programmer</li>|
      <li>Embedded Systems Tinkerer</li>|
      <li>Security Expert Wannabe</li>|
      <li>Part-time Open Source Advocate</li>|
      <li>Full-time Nerd</li>
    </ul>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
      <h3 class="text-center">Hello internet stranger! Welcome to my humble abode on the internet!</h3><br/>
      <p>I'm LA, a humble Software Developer / Embedded Systems hobbyist trying to keep up with the intense evolution of the world's technology stack. I'm currently a Full-stack PHP developer for <a href="https://express.yilinker.com/">Yilinker Express</a>, a courier delivery platform under the <a href="https://www.yilinker.com/">Yilinker</a> company umbrella where I'm part of the core development team tasked on designing and implementing the ever-changing requirements and features of the platform.</p>

      <p>On the side, I play CS:GO, come up with stupid ideas for a startup, find out whether it's the software or the hardware's fault on my failing mini projects, encrypt anything that is encryptable (and sometimes forget the passkey) and run around when my bottom hurts from sitting all day.</p>

      <p>Have a project in mind? Need an extra pair of hands on your repo? Just drop me a line and let's see what we can do together!</p>

    </div>
    <div class="col-md-2"></div>
  </div>
</div>

app/views/main/portfolio.html.erb
<% provide(:title, 'Portfolio') %>
<div class="container portfolio">
  <div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-10">
      <div class="media">
        <div class="media-left media-middle">
          <a href="#">
            <%= image_tag('yi_logo.jpg', alt: 'Yilinker logo') %>
          </a>
        </div>
        <div class="media-body">
          <h3 class="media-heading"><a href="https://www.yilinker.com/"><u>Yilinker</u></a></h3>
          Currently part of the core development team in-charge of planning and executing planned features and functions for the <a href="https://express.yilinker.com/"><u>courier platform</u></a> of the company.
        </div>
      </div>
    </div>
    <div class="col-md-1"></div>
  </div>
  <hr class="dashed">
  <div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-10">
      <div class="media">
        <div class="media-left media-middle">
          <a href="#">
            <%= image_tag('es_logo.jpg', alt: 'EasyShop logo') %>
          </a>
          <a href="#">
            <%= image_tag('ed_logo.png', alt: 'EasyDeals logo') %>
          </a>
        </div>
        <div class="media-body">
          <h3 class="media-heading"><a href="https://www.easyshop.ph/"><u>EasyShop</u></a> / <a href="https://www.easydeal.ph/"><u>EasyDeal</u></a></h3>
          Spearheaded migration from Structured Query Language (SQL) based queries on Models to Object-Relational Mapping (ORM) of EasyShop. Full-stack PHP developer.<br/><br/><br/><br/>Managed and maintained EasyDeal codebase by optimizing and refactoring existing features as well as augmenting the site with new functionalities.
        </div>
      </div>
    </div>
    <div class="col-md-1"></div>
  </div>
  <hr class="dashed">
  <div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-10">
      <div class="media">
        <div class="media-left media-middle">
          <a href="#">
            <%= image_tag('hgst_logo.png', alt: 'HGST logo') %>
          </a>
        </div>
        <div class="media-body">
          <h3 class="media-heading"><a href="https://www.hgst.com/"><u>HGST Philippines</u></a></h3>
          Designed and created a robust Python-based backend application for run-to-run control of Carbon thickness deposition on head sliders. Constructed various high-quality and reliable software for key slider procedures regarding automation, regulation, fault-detection and machine interdiction
        </div>
      </div>
    </div>
    <div class="col-md-1"></div>
  </div>
  <hr class="dashed">
  <div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-10">
      <div class="media">
        <div class="media-left media-middle">
          <a href="#">
            <%= image_tag('ss_logo.png', alt: 'SkillShot Labs logo') %>
          </a>
        </div>
        <div class="media-body">
          <h3 class="media-heading"><a href="http://skillshotlabs.com/"><u>Skillshot Labs</u></a></h3>
          Lead the development of an in-house library for peer-to-peer multiplayer game setup over Wi-Fi using Unity3D and Java.
        </div>
      </div>
    </div>
    <div class="col-md-1"></div>
  </div>
  <hr class="dashed">
  <div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-10 portfolio-1">
      <div class="media">
        <div class="media-left media-middle">
          <a href="#">
            <%= image_tag('ibm_logo.jpg', alt: 'IBM logo') %>
          </a>
        </div>
        <div class="media-body">
          <h3 class="media-heading"><a href="http://www.ibm.com/ph-en/"><u>IBM Philippines</u></a></h3>
          Helped restructuring and implementation of the network architecture of "Blue Room" (Server Test Room) which included creating a Storage Area Network (SAN) over Fibre Channel which enabled the servers to boot “over-the-network”. 
        </div>
      </div>
    </div>
    <div class="col-md-1"></div>
  </div>
  <hr class="dashed">
  <div class="row">
    <p class="text-center">All trademarks and registered trademarks are the property of their respective owners.</p>
  </div>
</div>